export {default as BackIcon} from '../assets/images/back.png';
export {default as BurgerMenuIcon} from '../assets/images/BurgerMenu.png';
export {default as NotificationsIcon} from '../assets/images/Notifications.png';
export {default as SearchIcon} from '../assets/images/search.png';
export {default as ShareIcon} from '../assets/images/ShareIt.png';
export {default as IntegrationIcon} from '../assets/images/Integration.png';
export {default as CompanyIcon} from '../assets/images/Company.png';
export {default as CompanyIconGray} from '../assets/images/CompanyIconGray.png';
export {default as EmailIcon} from '../assets/images/email-2.png';
export {default as PhoneIcon} from '../assets/images/local_phone.png';
export {default as LocationIcon} from '../assets/images/location_on.png';
export {default as LanguageIcon} from '../assets/images/language.png';
export {default as QrCodeIcon} from '../assets/images/qrCode.png';
export {default as AddButtonIcon} from '../assets/images/AddButton.png';
export {default as saveIcon} from '../assets/images/Save.png';
export {default as googleIcon} from '../assets/images/socials/google.png';
export {default as facebookIcon} from '../assets/images/socials/facebook.png';
export {default as appleIcon} from '../assets/images/socials/apple.png';
export {default as sendIcon} from '../assets/images/send.png';
export {default as scannerIcon} from '../assets/images/Scanner.png';
export {default as EyeIcon} from '../assets/images/eye.png';
export {default as EyeOffIcon} from '../assets/images/eye-off.png';
export {default as Photo} from '../assets/images/photo-skeleton.png';
export {default as CloseIcon} from '../assets/images/close-icon.png';
export {default as XIcon} from '../assets/images/close.png';
export {default as InstaIcon} from '../assets/images/socials/ic_instagram.png';
export {default as TwitterIcon} from '../assets/images/socials/ic_twitter.png';
export {default as LinkedIdIcon} from '../assets/images/socials/ic_linkedIn.png';
export {default as WhatsAppIcon} from '../assets/images/socials/ic_whatsapp.png';
export {default as addCardIcon} from '../assets/images/add_card.png';
export {default as MenuIcon} from '../assets/images/menu.png';
export {default as PencilIcon} from '../assets/images/pencil.png';
export {default as newLogo} from '../assets/images/newLogo.png'
export {default as aboutLogo} from '../assets/images/drawer/about.png'
export {default as feedbackLogo} from '../assets/images/drawer/feedback.png'
export {default as guideLogo} from '../assets/images/drawer/guide.png'
export {default as licenceLogo} from '../assets/images/drawer/licence.png'
export {default as logoutLogo} from '../assets/images/drawer/logout.png'
export {default as privacyLogo} from '../assets/images/drawer/privacy.png'
export {default as ratingsLogo} from '../assets/images/drawer/ratings.png'
